export const ActionTypes = {
    NAV_ELEMENT_CLICK: 'NAV_ELEMENT_CLICK',
    CHANGE_URL_STARTED: 'CHANGE_URL_STARTED',
    CHANGE_URL_FINISHED: 'CHANGE_URL_FINISHED',
    ADD_ARTICLE_FILTER_RULE: 'ADD_ARTICLE_FILTER_RULE',
    SUB_NAV_ELEMENT_CLICK: 'SUB_NAV_ELEMENT_CLICK',
    RECEIVED_ARTICLES: 'RECEIVED_ARTICLES',
    RECEIVED_API_DATA: 'RECEIVED_API_DATA',
    API_REQUEST_SEND: 'API_REQUEST_SEND'
};