export const NAV_ELEMENT_CLICK =            'NAV_ELEMENT_CLICK';
export const ADD_ARTICLE_FILTER_RULE =      'ADD_ARTICLE_FILTER_RULE';
export const DELETE_ARTICLE_FILTER_RULE =   'DELETE_ARTICLE_FILTER_RULE';
export const RECEIVED_ARTICLES =            'RECEIVED_ARTICLES';